### ISSUE TITLE
lorthon.so: undefined symbol: _py.ZeroStruct

### ISSUE THREAD

**Issue by jepra** [galalmounir/lorthon#2]
i run test.py file in this directory (lorthon/tst/)

but there is error in line 1, where lorthon.so:undefined symbol:_py.ZeroStruct

i'm using Raspberry Pi 3 B+
and running test.py with Thonny, python IDE from Raspbian

**Comment by galalmounir** [comment]
This is an issue because of Python3. Please use Python 2.

I am currently working on Python3 support

**Comment by jepra** [comment]
Thankyou for your reply, but i have a question, why when i send data From
LoRa Node (RFM95), the Gateway (RHF0M301) can't received the data From the
Node ? Maybe u have Arduino Node Example Code.

In this case, i want build Private Network Gateway, Where the Data From
Node can Stored to Database.

My Scenario :

- Gateway Using Rapsberry Pi 3 B+ & RHF0M301 Concentrator
- Nodes Using Arduino Nano & HopeRFM95W

Thankyou 🙏

**Comment by galalmounir** [comment]
There are a few things you might want to double check.

Are the radio settings on your RFM95 the same as the gateway? Make sure that your global.json file contains the correct radio settings you are using for transmission from your nodes RFM95.

Also, double check the IQ inversion setting on the RFM95.

I do not have an Arduino node code unfortunately.
